//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movement
    {
        public int id { get; set; }
        public string movement_ID { get; set; }
        public string stock_code { get; set; }
        public string compartment_ID { get; set; }
        public string request_ID { get; set; }
        public int quantity_supplied { get; set; }
        public string issued_by { get; set; }
        public string received_by { get; set; }
        public string transaction_type_ID { get; set; }
        public Nullable<System.DateTime> date_received { get; set; }
        public Nullable<int> return_status { get; set; }
        public Nullable<System.DateTime> expected_return_date { get; set; }
        public Nullable<System.DateTime> return_date { get; set; }
    
        public virtual Employee_Details Employee_Details { get; set; }
        public virtual Employee_Details Employee_Details1 { get; set; }
        public virtual Return_Status Return_Status1 { get; set; }
        public virtual Stock_Details Stock_Details { get; set; }
        public virtual Type_of_Transaction Type_of_Transaction { get; set; }
    }
}
